version: '3'
services:
  flask-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
    command: flask run --host=0.0.0.0
    env_file:
      - .env
  queue:
    build: .
    ports:
      - "8080:8080"
    command: python3 queue_manager.py
    env_file:
      - .env


